import localFont from "next/font/local";
import Header from "../app/component/Header/page"
import HeaderMain from "../app/component/HeaderMain/page"
import Navbar from "../app/component/navbar/page"

import "./globals.css";
export const metadata = {
  title: "E-Commerce Website ||NEXT APP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href="https://cdn.jsdelivr.net/npm/remixicon/fonts/remixicon.css" rel="stylesheet"/>

      </head>
      <body className="container">
        <Header/>
        <HeaderMain/>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
